### ISSUE TITLE
Allegato 6: dubbi emersi in fase di analisi delle nuove linee guida

### ISSUE THREAD

**Issue by alessandra-211177** [AgID/protocollo-comunicazione-aoo#10]
Come da precedenti contatti riepiloghiamo le questioni emerse negli scambi con voi (AgiD) a beneficio di chi dovrà analizzare l’allegato 6. Dividiamo le domande per tematica. 
Le domande contrassegnate con [*] sono emerse in seguito ai precedenti confronti (o sono state integrate con nuovi dettagli).

**1.	IPA – Indice Pubbliche Amministrazioni**
_1.1	Recupero domicilio della AOO da IPA e comunicazione end-to-end_ 
Per scambiare un messaggio tra AOO prenderemo il tipo domicilio da IPA. Nelle API di IPA che riportano il domicilio (rif. http://www.indicepa.gov.it/public-ws/WS09_DOM_DIG_AOO.php) esiste la tipologia del domicilio (per ora solo PEC) e il domicilio digitale della AOO. Verrà aggiunta un’informazione contenente gli endpoint dei ws soap mittente e destinatario?
Se presenti manderemo il messaggio come definito nel wsdl: lo manderemo direttamente all'endpoint della AOO destinataria (che sarà un servizio esposto su Internet in https da una AOO di altro Ente) senza l’intermediazione delle porte spCoop. È corretto?

_1.2	IPA – modalità di accesso ai dati_
IPA ci ha comunicato che non sarà più aggiornata la modalità di fruizione attraverso LDAP. Continueranno ad essere disponibili Open Data e API. Sarà messa a disposizione una nuova fruizione via SPARQL che però ci sembra non essere ancora disponibile.
Via Open Data è necessario scaricare ogni volta tutti i dati. Non esiste una modalità incrementale. Sarà disponibile con la fruizione via SPARQL? Quando se ne prevede la disponibilità?

_1.3	Aggiornamento endpoint su IPA – dove pubblicheremo l’endpoint del servizio?_
Attualmente nei dati di IPA è presente il tipo domicilio e l’indirizzo PEC. NON è previsto un campo specifico per i servizi. Verranno utilizzati gli stessi campi (più riferimenti di diverso tipo per la stessa AOO) oppure ci saranno degli attributi specifici?
L’AOO potrà avere più domicili della stessa tipologia? Oppure avrà una PEC e una coppia di endpoint per invioMessaggio e invioConferma?

_1.4	[*] Politiche di retry e switch da un canale ad un’altro_
Quali sono le politiche di retry? Nel caso di esistenza di entrambi i domicili per una AOO (sia servizi SOAP che PEC) e assunto che la tipologia prioritaria per la comunicazione sarà servizi, è previsto che si facciamo una serie di tentativi su un canale e poi si passi al secondo canale in caso di indisponibilità del primo? Quanti sono i tentativi da effettuarsi? Ci sono casi in cui dopo il primo tentativo si può assumere che con tale canale non otterrò mai risposta (mancata configurazione)?
Potrò ottenere dai servizi risposte tipo “Sistema non disponibile, riprova tra 10 minuti? Oppure i tentativi sono da intendersi sequenziali in un tempo massimo che può essere costituito dal timeout?

**2	SIGILLO ELETTRONICO**
_2.1	[*] Sigillo Elettronico: si tratta di un sigillo unico per tutto l’Ente o uno per AOO?_ 
Il Sigillo è da intendersi per AOO o per Ente in qualità di soggetto giuridico?
Se fosse per AOO, ogni volta che una AOO viene chiusa dovrebbe essere applicato un processo di revoca sigillo per la aoo vecchia e richiesta sigillo per la aoo nuova. Ci sono Enti che hanno molte AOO.
Possono essere rilasciati più Sigilli per lo stesso Ente?

**3	AMBIENTE DI TEST E COLLAUDO**
_3.1	Esiste un ambiente di test e se si quali sono le modalità per attivarlo?_
Tale domanda è riferita sia ad IPA che a controparti di Enti che vorrebbero provare il loro servizio prima della messa in produzione.

_3.2	È previsto un collaudo dei servizi dell’Ente prima che questi vadano in produzione?_ 
AgiD prevede di verificare quanto implementato non tanto in termini di implementazione stessa, ma di _SLA_ che il servizio deve garantire. Quale può essere un tempo di risposta accettabile?

**4	WS SOAP INTEROPERABILITA’ e PEC** 
_4.1	[*] Possiamo essere certi che chi implementa MessageInoltroResponse implementi anche la ConfermaMessaggioInoltro?_
La conferma, seppure asincrona, chiude il ciclo di una comunicazione avvenuta correttamente. È presumibile che in seguito ad essa sui nostri sistemi possa succedere qualcosa.
Se arrivasse il messaggio ma non la conferma cosa si dovrebbe fare? Rimandare il messaggio? E quindi lato ricezione prevedere anche che potrebbe arrivare due volte la ricezione e che quindi la seconda verrà scartata.
Supponendo un cruscotto di gestione dei messaggi avremo un cambio di stato in “preso in carico dalla AOO destinataria” quando otterremo la response sincrona MessageInoltroResponse, e un “ricevuta correttamente dalla AOO destinataria” in seguito alla nostra ricezione di una request ConfermaMessaggioInoltro con al suo interno un esito positivo. Se questo secondo messaggio non dovesse arrivare è previsto o si prevederà un modo per “richiedere” lo stato di ricezione (magari su un gruppo di messaggi?)  

_4.2	Le PEC verso i privati. Il titolo della sezione rimanda solo alla comunicazione tra AOO._ 
La PEC verso i privati continuerà ad essere un canale valido? E se sì, dovranno avere la stessa Segnatura descritta nell'allegato 6? Nel vecchio xsd della Segnatura c'erano le istruzioni per l'invio delle notifiche di annullo ad es. Nel nuovo xsd le ricevute non ci sono più. L’annullo da parte di mittente o destinatario è gestito come messaggio a parte.

**5	MESSAGGIO PROTOCOLLO XSD**
_5.1	[*] Relazione 1:1 tra Documento e contenuto fisico_
Il messaggio di protocollo (MessaggioProtocolloType) ha al suo interno, oltre alla segnatura, il Documento stesso che è di tipo FileType
 _<xsd:element name="Documento" type="msgprot:FileType"/>_
che corrisponde al contenuto fisico. Non sarebbe più “versatile” avere uno o più Contenuti all’interno del Documento e caratterizzare loro come FileType anziché il documento stesso? Rispetto alla nostra struttura attuale ci semplificherebbe alcune casistiche come quella descritta nel punto successivo (marca e firma detached).

_5.2	[*] Marca detached e Firma detached_
Nel caso di documento con marca temporale detached...come possiamo fare? C'è la possibilità di marcare un unico documento principale (che è 1:1 con un contenuto fisico). La marca però non può essere considerata un allegato a nostro avviso e altrettanto la firma. Potremmo avere più marche e più firme a fronte di un documento. 

**6	SEGNATURA XSD**
_6.1	Nel nuovo xsd della Segnatura manca la possibilità di indicare se il destinatario è una persona giuridica_ (si faccia riferito a SoggettoType)

_6.2	Link e gestione messaggi di grandi dimensioni_
Nella versione della Segnatura attuale, per il documento si può indicare un link nel formato url da cui reperire un documento, in alternativa ad allegarlo alla mail PEC (per file audio, video ad es. con dimensioni non inviabili). Per i servizi avremo lo stesso problema in assenza del link.
Nella nuova Segnatura non c'è più la possibilità di definire tali link. Come possiamo gestire questa casistica? 

_6.3	[*] Perché il tag `<CodiceFiscale>` non è obbligatorio quanto invece lo si richiede obbligatorio nei metadati descritti nell’allegato 5?_

_6.4	[*] Perché il sottotag della Segnatura `<IndirizzoTelematico>` del tag `<Persona>` è obbligatorio?_ 
Non tutti i cittadini hanno un indirizzo telematico: se un cittadino dovesse portare un’istanza a mano presso uno sportello dell’Ente potrebbe non essere disponibile tale informazione.

_6.5	[*] Nei procedimenti amministrativi in cui la protocollazione in uscita è un portale, dove / come censiamo questa informazione?_
Potrebbe essere ricondotta all’ `<indirizzoTelematico>` indicato nella Segnatura?
E in tal caso sarebbe di tipo url o other?   - _url, nel caso di interfacce di servizio (API REST o SOAP) o - other, in casi differenti dai precedenti_	
Supponiamo il caso in cui un domani sull’app IO il cittadino dovesse recuperare un procedimento amministrativo fatto presso l’Ente.

_6.6	[*] Tutti i sotto tag di `<IndirizzoPostale>` devono essere compilati minuziosamente oppure potremo alimentare solo quelli che ho e aggirare l’obbligatorietà mettendo un tag vuoto?_

_6.7	il sottotag <Nazione> del tag `<IndirizzoPostale>` non sarebbe più corretto chiamarlo `<Stato>` per gestire anche il caso di apolidi?_ Osservazione riportata dagli Enti

**Comment by vintra73** [comment]
Buongiorno, nel confermare quanto indicato per le vie brevi, di seguito le nostre in merito ai quesiti/dubbi espressi

**Comment by vintra73** [comment]
1. IPA – Indice Pubbliche Amministrazioni
1.1 Recupero domicilio della AOO da IPA e comunicazione end-to-end
Per scambiare un messaggio tra AOO prenderemo il tipo domicilio da IPA. Nelle API di IPA che riportano il domicilio (rif. http://www.indicepa.gov.it/public-ws/WS09_DOM_DIG_AOO.php) esiste la tipologia del domicilio (per ora solo PEC) e il domicilio digitale della AOO. Verrà aggiunta un’informazione contenente gli endpoint dei ws soap mittente e destinatario?
Se presenti manderemo il messaggio come definito nel wsdl: lo manderemo direttamente all'endpoint della AOO destinataria (che sarà un servizio esposto su Internet in https da una AOO di altro Ente) senza l’intermediazione delle porte spCoop. È corretto?

**RISPOSTA: SI**

**Comment by vintra73** [comment]
1.2 IPA – modalità di accesso ai dati
IPA ci ha comunicato che non sarà più aggiornata la modalità di fruizione attraverso LDAP. Continueranno ad essere disponibili Open Data e API. Sarà messa a disposizione una nuova fruizione via SPARQL che però ci sembra non essere ancora disponibile.
Via Open Data è necessario scaricare ogni volta tutti i dati. Non esiste una modalità incrementale. Sarà disponibile con la fruizione via SPARQL? Quando se ne prevede la disponibilità?

**RISPOSTA: L'attuale roadmap di evoluzione di IPA aggiunge nuove modalità per la fruizione dei dati preservando le attuali modalità, sono un fase di ultimazione le implementazioni e il collaudo delle realizzazioni.**

**Comment by vintra73** [comment]
1.3 Aggiornamento endpoint su IPA – dove pubblicheremo l’endpoint del servizio?
Attualmente nei dati di IPA è presente il tipo domicilio e l’indirizzo PEC. NON è previsto un campo specifico per i servizi. Verranno utilizzati gli stessi campi (più riferimenti di diverso tipo per la stessa AOO) oppure ci saranno degli attributi specifici?
L’AOO potrà avere più domicili della stessa tipologia? Oppure avrà una PEC e una coppia di endpoint per invioMessaggio e invioConferma?

**RISPOSTA: Nell'agiornamento dell'IPA indicato alla precedente risposta evidenzio che la nuova versione dell'IPA prevede l'aggiunta di attributi specifici per gli enpoint, in relazione alle numerosità si preservano le attuali possibilità per le PEC mentre, di contro, per i WS sarà possibile indicare gli endpoint per i servizi ProtocolloDestinatarioService e ProtocolloMittenteService**

**Comment by vintra73** [comment]
"2 SIGILLO ELETTRONICO
2.1 [*] Sigillo Elettronico: si tratta di un sigillo unico per tutto l’Ente o uno per AOO?
Il Sigillo è da intendersi per AOO o per Ente in qualità di soggetto giuridico?
Se fosse per AOO, ogni volta che una AOO viene chiusa dovrebbe essere applicato un processo di revoca sigillo per la aoo vecchia e richiesta sigillo per la aoo nuova. Ci sono Enti che hanno molte AOO.
Possono essere rilasciati più Sigilli per lo stesso Ente?"

**RISPOSTA: La policy in merito alla associazione del sigillo a livello di AOO o Ente è nella discrezionalità delle Amministrazioni che si organizzano e gestiscono i relativi processi (ad esempio certificate revocation) in conseguenza delle scelte effettuate, Si evidenzia che il tag SegnaturaInformaticaType\Intestazione\Identificatore del namespace http://www.agid.gov.it/protocollo/ permette in ogni caso la AOO.**

**Comment by vintra73** [comment]
3 AMBIENTE DI TEST E COLLAUDO
3.1 Esiste un ambiente di test e se si quali sono le modalità per attivarlo?
Tale domanda è riferita sia ad IPA che a controparti di Enti che vorrebbero provare il loro servizio prima della messa in produzione.

**RISPOSTA: Allo stato non sono previsti ambienti di test. **

**Comment by vintra73** [comment]
3.2 È previsto un collaudo dei servizi dell’Ente prima che questi vadano in produzione?
AgiD prevede di verificare quanto implementato non tanto in termini di implementazione stessa, ma di SLA che il servizio deve garantire. Quale può essere un tempo di risposta accettabile?

**RISPOSTA: Non è previsto il calludo reputando esaustivo la dichiarazione delle specifiche che le amministrazioni implementano. Relativamente alla verifica degli SLA prevediamo "errata corrige" dell'allegato 6 in cui saranno indicati gli stessi.**

**Comment by vintra73** [comment]
4 WS SOAP INTEROPERABILITA’ e PEC
4.1 [*] Possiamo essere certi che chi implementa MessageInoltroResponse implementi anche la ConfermaMessaggioInoltro?
La conferma, seppure asincrona, chiude il ciclo di una comunicazione avvenuta correttamente. È presumibile che in seguito ad essa sui nostri sistemi possa succedere qualcosa.
Se arrivasse il messaggio ma non la conferma cosa si dovrebbe fare? Rimandare il messaggio? E quindi lato ricezione prevedere anche che potrebbe arrivare due volte la ricezione e che quindi la seconda verrà scartata.
Supponendo un cruscotto di gestione dei messaggi avremo un cambio di stato in “preso in carico dalla AOO destinataria” quando otterremo la response sincrona MessageInoltroResponse, e un “ricevuta correttamente dalla AOO destinataria” in seguito alla nostra ricezione di una request ConfermaMessaggioInoltro con al suo interno un esito positivo. Se questo secondo messaggio non dovesse arrivare è previsto o si prevederà un modo per “richiedere” lo stato di ricezione (magari su un gruppo di messaggi?)

**RISPOSTA: L'allegato 6 prevede che le amministrazioni implementino ambedue i services ProtocolloDestinatarioService e ProtocolloDestinatarioService. Avendo applicato un pattern di interazione non bloccante RPC PUSH la comunicazione si ritiene conclusa alla ricezione della conferma.Per la gestione delle comunicazione non completate, come indicato in precedenza, prevediamo "errata corrige" dell'allegato 6 per indicare le policy di retry.**

**Comment by vintra73** [comment]
4.2 Le PEC verso i privati. Il titolo della sezione rimanda solo alla comunicazione tra AOO.
La PEC verso i privati continuerà ad essere un canale valido? E se sì, dovranno avere la stessa Segnatura descritta nell'allegato 6? Nel vecchio xsd della Segnatura c'erano le istruzioni per l'invio delle notifiche di annullo ad es. Nel nuovo xsd le ricevute non ci sono più. L’annullo da parte di mittente o destinatario è gestito come messaggio a parte.

**RISPOSTA: Il perimentro dell'allegato non ha impatti nella comunicazioni con i privati, in merito alle fattispecie indicate nella indicata "errata corrige" dell'allegato 6 provvediamo ad arrichire i data type per la gestione delle stesse.**

**Comment by vintra73** [comment]
5 MESSAGGIO PROTOCOLLO XSD
5.1 [*] Relazione 1:1 tra Documento e contenuto fisico
Il messaggio di protocollo (MessaggioProtocolloType) ha al suo interno, oltre alla segnatura, il Documento stesso che è di tipo FileType
<xsd:element name="Documento" type="msgprot:FileType"/>
che corrisponde al contenuto fisico. Non sarebbe più “versatile” avere uno o più Contenuti all’interno del Documento e caratterizzare loro come FileType anziché il documento stesso? Rispetto alla nostra struttura attuale ci semplificherebbe alcune casistiche come quella descritta nel punto successivo (marca e firma detached).

**RISPOSTA: Nell'XSD individuato dal namespace http://www.agid.gov.it/protocollo/ non si riscontra la presenza dell'element Documento, in merito al trasposto del documento primario e degli allegati si evidenzia che il type DescrizioneType prevede gli elementi DocumentoPrimario e Allegato rispettivamente con cardinalità 1..1 e 0..n."

**Comment by vintra73** [comment]
5.2 [*] Marca detached e Firma detached
Nel caso di documento con marca temporale detached...come possiamo fare? C'è la possibilità di marcare un unico documento principale (che è 1:1 con un contenuto fisico). La marca però non può essere considerata un allegato a nostro avviso e altrettanto la firma. Potremmo avere più marche e più firme a fronte di un documento.


**RISPOSTA: Nella indicata "errata corrige" dell'allegato 6 provvediamo ad arrichire i data type per la gestione delle casistiche detached.**

**Comment by vintra73** [comment]
6 SEGNATURA XSD
6.1 Nel nuovo xsd della Segnatura manca la possibilità di indicare se il destinatario è una persona giuridica (si faccia riferito a SoggettoType)

**RISPSOTA: Nella indicata "errata corrige" dell'allegato 6 provvediamo ad aggiornare il type SoggettoType**

**Comment by vintra73** [comment]
6.2 Link e gestione messaggi di grandi dimensioni
Nella versione della Segnatura attuale, per il documento si può indicare un link nel formato url da cui reperire un documento, in alternativa ad allegarlo alla mail PEC (per file audio, video ad es. con dimensioni non inviabili). Per i servizi avremo lo stesso problema in assenza del link.
Nella nuova Segnatura non c'è più la possibilità di definire tali link. Come possiamo gestire questa casistica?

**RISPOSTA: Non si ravvede la problematica per l'inoltro di file di grandi dimensioni tramite WS, si ricorda che nell'allegato 6 è indicato che "Per l'inoltro di binary data nei messaggi SOAP si assume l’adozione del W3C Message Transmission Optimization Mechanism". In merito alla gestione dei file di grandi dimensioni nel caso di PEC si provvederà, nella indicata "errata corrige" dell'allegato 6, di rintrodurre la possibilità di indicare un URL per recuperare i documenti di grandi dimensioni e decorare lo stesso con l'indicazione del time to live della risorsa**

**Comment by vintra73** [comment]
6.3 [*] Perché il tag <CodiceFiscale> non è obbligatorio quanto invece lo si richiede obbligatorio nei metadati descritti nell’allegato 5?

**RISPOSTA: In meriito all'allegato 6 si è derivata l'obbligatorietà dalla vecchia versione della segnatura.**

**Comment by vintra73** [comment]
6.4 [*] Perché il sottotag della Segnatura <IndirizzoTelematico> del tag <Persona> è obbligatorio?
Non tutti i cittadini hanno un indirizzo telematico: se un cittadino dovesse portare un’istanza a mano presso uno sportello dell’Ente potrebbe non essere disponibile tale informazione.

**RISPOSTA: Nella indicata "errata corrige" dell'allegato 6 provvediamo ad aggiornare l'indicata obbligatorietà.**

**Comment by vintra73** [comment]
6.5 [*] Nei procedimenti amministrativi in cui la protocollazione in uscita è un portale, dove / come censiamo questa informazione?
Potrebbe essere ricondotta all’ <indirizzoTelematico> indicato nella Segnatura?
E in tal caso sarebbe di tipo url o other? - url, nel caso di interfacce di servizio (API REST o SOAP) o - other, in casi differenti dai precedenti
Supponiamo il caso in cui un domani sull’app IO il cittadino dovesse recuperare un procedimento amministrativo fatto presso l’Ente.

**@alessandra-211177 Non è chiaro lo scenario prospettato, sarebbe possibile avere maggiori indicazioni**

**Comment by vintra73** [comment]
6.6 [*] Tutti i sotto tag di <IndirizzoPostale> devono essere compilati minuziosamente oppure potremo alimentare solo quelli che ho e aggirare l’obbligatorietà mettendo un tag vuoto?

6.7 il sottotag del tag <IndirizzoPostale> non sarebbe più corretto chiamarlo <Stato> per gestire anche il caso di apolidi? Osservazione riportata dagli Enti

**RISPOSTA: Non abbiamo considerato l'ipotesi di coordinate non complete, ci si chiede mi chiede il valore di un'indirizzo in assenza di parte di degli elementi individuati. Si evidenzia che l'attualmente il type IndirizzoPostaleType prevede:

         <xs:element name="Toponimo" type="prot:ToponimoType"/>
         <xs:element name="Civico" type="xs:string"/>            
         <xs:element name="CAP" type="prot:CAPType"/>
         <xs:element name="Comune" type="prot:ComuneType"/>                                        
         <xs:element name="Nazione" default="Italia">

Nella precedente versione (type Indirizzo) era:

           <xs:element ref="tns:Toponimo"/>
           <xs:element ref="tns:Civico"/>
           <xs:element ref="tns:CAP"/>
           <xs:element ref="tns:Comune"/>
           <xs:element ref="tns:Provincia"/>
           <xs:element ref="tns:Nazione" minOccurs="0"/>**

**Comment by alessandra-211177** [comment]
> 6.5 [*] Nei procedimenti amministrativi in cui la protocollazione in uscita è un portale, dove / come censiamo questa informazione?
> Potrebbe essere ricondotta all’ indicato nella Segnatura?
> E in tal caso sarebbe di tipo url o other? - url, nel caso di interfacce di servizio (API REST o SOAP) o - other, in casi differenti dai precedenti
> Supponiamo il caso in cui un domani sull’app IO il cittadino dovesse recuperare un procedimento amministrativo fatto presso l’Ente.
> 
> **@alessandra-211177 Non è chiaro lo scenario prospettato, sarebbe possibile avere maggiori indicazioni**


Ci stiamo ponendo il caso in cui un procedimento amministrativo non è creato nel nostro sistema documentale ma su un sistema terzo. 
Supponiamo un cittadino che richieda un certificato (non so se è proprio un caso calzante) da un portale esterno al nostro sistema documentale. Tale portale permette l'inserimento e l'iter autorizzativo di predisposizione di tale certificato.
Ad un certo punto tale portale comunica con il nostro modulo di protocollo per protocollare in uscita e inviare al destinatario.
Ma non verrà inviata né una pec al destinatario, né attivato un interscambio tra AOO.
Il messaggio verrà inviata al portale chiamante o ad altra app (supponevamo un domani l'app IO): il cittadino si collegherà con il suo SPID e potrà scaricare il certificato.
Ci chiedevamo se / dove inserire il destinatario "reale" (il portale che mette a disposizione del cittadino il certificato), 
come mantenere il destinatario "ufficiale" (comunque solo quel cittadino potrà scaricare il suo certificato)
ed eventualmente anche come potrebbe avvenire l'interazione tra il documentale e l'altro sistema (magari uno strato di servizi parallelo ai ws di interscambio tra aoo ma non necessariamente uguale) 
e se tali dati abbia senso siano contenuti nella Segnatura o nei metadati del documento stesso.

**Comment by vintra73** [comment]
@alessandra-211177 ti segnalo che il caso da te indicato esula dall'oggetto dell'allegato 6, 

In merito alla segnatura evidenzio che in essa deve essere indicato il soggetto destinatario della stessa, quindi nel caso descritto il cittadino. 

La comunicazione tra componenti (nel tuo esempio Portale e Sistema Documentale) sono interazioni interne al dominio dell'amministrazione che sulla base delle proprie esigenze organizzative definisce le modalità di colloquio delle stesse e le evidenze da registrare per gli scambi tra esse. 

Nell'ottica di efficientare la spesa e capitalizzare il knowhow della pubblica amministrazione, considerato che il MODI individua le API quale strumento ICT per l'interoperabilità tra diverse amministrazione, è auspicabile che anche internamente al dominio della singola amministrazioni si utilizzano le API.
