### ISSUE TITLE
CHIARIMENTO: PEC protocollo di comunicazione immutato

### ISSUE THREAD

**Issue by vintra73** [AgID/protocollo-comunicazione-aoo#12]
La possibilità di utilizzare la modalità di comunicazione tramite posta elettronica certificata (PEC) è da intendersi quale modalità residuale in attesa che tutte le AOO provvedono ad attrezzarsi con gli opportuni strumenti per l’utilizzo dei WS SOAP. 

L’intenzione nel predisporre l’allegato è stata quella di favorire l’adozione della modalità di comunicazione tra AOO realizzata tramite WS SOAP.  

Il protocollo di comunicazione, comprensivo degli oggetti dei messaggi scambiati, per le comunicazioni tramite PEC resta immutato rispetto a quanto indicato nella [Circolare AgID 60/2013](https://www.agid.gov.it/sites/default/files/repository_files/circolari/circolare_60_2013_segnatura_protocollo_informatico_-_rev_aipa_n.28-2001.pdf),  fatta salva la sostituire del type <Segnatura> nel namespace http://www.digitPa.gov.it/protocollo/ con il type <SegnaturaInformaticaType> nel namespace http://www.agid.gov.it/protocollo/.

**Comment by franthemanIT** [comment]
Un chiarimento sul chiarimento: cio' significa che, in attesa che tutte le AOO si attrezzino per l'uso dei WS SOAP, continuiamo a scambiarci PEC con l'attuale segnatura.xml priva di sigillo qualificato?
Se è così sarà consentito o vietato scambiarsi PEC con la "nuova" segnatura sigillata?


PS: mi sembra che i due link per i namespace non conducano a informazioni significative

**Comment by franthemanIT** [comment]
Mi permetto di sollecitare un riscontro, il tempo per le decisioni di un'amministrazione in vista del 7 giugno è ormai giunto.
Non mi è chiaro se, per gli invii via PEC:
1. si continua a usare il precedente schema XSD della segnatura (e dei messaggi successivi) e si cambia solo il riferimento al namespace nel preambolo del file segnatura.xml;
2. si usa il nuovo schema XSD per la segnatura (e per i messaggi successivi) ma non si appone il sigiillo.

Purtroppo ho difficoltà a interpretare il significato di "type nel namespace".
Chiedo inoltre se questa deroga alle linee guida sia formalizzata anche altrove.

**Comment by vintra73** [comment]
@franthemanIT crediamo di aver chiarito i dubbi da lei espressi in https://github.com/AgID/protocollo-comunicazione-aoo/tree/fixbug-2021

**Comment by franthemanIT** [comment]
Grazie,
Il tree del bugfix mi pare pero' confermare che dal 7 giugno si debba usare anche per i messaggi PEC la "nuova" segnatura.
Mi sfugge quindi il senso di questo chiarimento, oppure ci leggo io qualcosa che va oltre le sue intenzioni : se uso la nuova segnatura, che ha tag diversi, che ha il sigillo qualificato che prima non c'era ecc.., cosa resta "immutato" rispetto a prima?

**Comment by gawelfight** [comment]
Buongiorno, non ci sono chiarimenti in merito alla domanda di franthemanIT ?
Il quesito è semplice: nella Segnatura standard i tag dell'xml contenuto nella e-mail sono di numero contenuto e inizia con <Segnatura>. Dalle specifiche mi risulta CHIARO che la NUOVA SEGNATURA con primo tag "<prot:SegnaturaInformatica> sia solamente da utilizzare nelle comunicazioni Soap (quindi solo tra webservice e NON da allegare alle Pec).

Potete delucidarmi?
Grazie

**Comment by gawelfight** [comment]
Quando si commenta i Tag vengono tolti....intendevo: " nella Segnatura standard i tag dell'xml contenuto nella e-mail sono di numero contenuto e inizia con Segnatura "
