### ISSUE TITLE
Allegato 6: dubbi emersi in fase di analisi delle nuove linee guida 2

### ISSUE THREAD

**Issue by alessandra-211177** [AgID/protocollo-comunicazione-aoo#13]
**1)  Endpoint su IPA a livello di AOO, mentre le PEC sembrano anche a livello di settore**
Alcuni Enti hanno una struttura molto articolata di AOO e Settori sottostanti.
Prendiamo ad esempio Regione Piemonte con la AOO A1000A - DIREZIONE DELLA GIUNTA REGIONALE.
Tale AOO ha la sua PEC direzionegiunta@cert.regione.piemonte.it .
In questo momento però le trasmissioni di protocollo non sempre vengono inviate alla PEC dell'AOO, ma alle PEC del settore sottostante (ad es. regionali@cert.regione.piemonte.it).
Se abbiamo inteso correttamente l'allegato, in futuro tutto arriverà ad un unico _endpoint_ della AOO. Come va interpretato il processo di smistamento sul settore? Potrebbe essere un valore contenuto nel messaggio stesso ad indicare il settore?

**2)  Il nuovo protocollo di comunicazione tra AOO via web services prevede il riconoscimento delle due controparti:** entrambe dovranno pubblicare il loro endpoint su IPA.
Nel processo attuale, con la PEC, due AOO che devono scambiarsi un documento non devono stipulare alcun accordo formale. Con la PEC non è previsto un riconoscimento delle due parti precedente allo scambio. Nel momento in cui si deve inviare un documento protocollato ad una AOO mai contattata in precedenza, viene indicato il suo indirizzo PEC. 
Con il nuovo interscambio invece si prevede una sorta di accordo formale e di registrazione delle chiavi pubbliche del certificato affinché le due parti possano “colloquiare”:
L’instaurazione del canale dovrà essere fatta a seguito di una mutua autenticazione attraverso l’uso di certificati X509 V3 (tipicamente attraverso la verifica del campo subject DN dello stesso certificato). Le amministrazioni dovranno dotarsi dei certificati autonomamente
Dal punto di vista organizzativo questa nuova condizione potrebbe costituire uno scoglio. Come potrebbe essere mitigato l’impatto sull’Ente?

**3)  La Segnatura dovrà essere firmata attraverso Sigillo Elettronico qualificato (sia via PEC che sul canale WS-SOAP): se tale Sigillo fosse scaduto quando effettuo la verifica?**
Se il Sigillo che garantisce l’integrità fosse valido nel momento in cui lo appongo (supponiamo in data odierna avvenga la protocollazione in uscita) ma l’AOO ricevente dovesse protocollare in ingresso tra un mese, quel Sigillo potrebbe non essere più valido. 
Cosa posso fare al fine di non far scadere il Sigillo elettronico qualificato della mia AOO? 
Nelle specifiche non abbiamo trovato riferimenti al momento in cui vada verificata la validità del sigillo sulla Segnatura. Crediamo sia da intendersi all'apposizione della stessa. Si parla genericamente di errore "001_ValidazioneFirma".
Dai wsdl vediamo che tale validazione è nella _ResponseMessaggioInoltro_, quindi sembrerebbe da intender-si valida alla data della trasmissione, non necessariamente a quella della protocollazione in ingresso a seguito della quale viene inviata la conferma. Se la trasmissione non fosse contestuale alla protocollazione in uscita (oggi protocollo e domani invio la segnatura, magari per tempi tecnici dell'ente) potrei comunque inviare una Segnatura con un Sigillo scaduto. Quali tipi di controlli dovrei applicare?
Quella degli allegati invece viene verificata in fase di conferma (006_DocumentoAllegatiErroreValidazioneSigillo) e a quel punto, il Sigillo potrebbe essere scaduto.

**4)  Cosa significa l'errore "000_Irricevibilita"?** 
Si tratta di un errore per processo interno dell'Ente? Un funzionario, dopo che il messaggio è arrivato correttamente ed ha passato i controlli formali, entra nel merito per protocollarlo e si accorge ad esempio che un allegato è in formato zip.  Anche se tale formato è ammesso, il suo ufficio accetta solo pdf, quindi a quel punto rifiuta per irricevibilità e specifica di ritrasmettere il messaggio con il formato richiesto dal suo standard interno. È corretta questa interpretazione? L'errore di irricevibilità ci sembra avvenga dopo una serie di altri controlli.

**5)  Può verificarsi il caso in cui l’invio della Segnatura avvenga su canale a servizi e la conferma arrivi invece via PEC (o viceversa)?** 
La nostra AOO effettuerà una serie di tentativi di invio a servizi e poi, non riuscendoci, cambierà canale di trasmissione passando alla PEC per indisponibilità del primo. Il ricevente successivamente prova a contattarmi per la conferma e riesce a farlo sul canale prioritario. Oppure succede l’esatto opposto. La conferma potrebbe avvenire anche molto tempo dopo la trasmissione di protocollo (dalla documentazione si evince che il messaggio di conferma viene inviato solo quando l'AOO ricevente protocolla in ingresso).
Si può verificare questa condizione? I sistemi di invio e ricezione sono separati, potrebbe non essere raggiungibile uno mentre l’altro si. Deve essere fatto un controllo sul canale di trasmissione? Se ricevo il messaggio inoltro a servizi devo trasmettere necessariamente la conferma di ricezione del messaggio a servizi?

**Comment by vintra73** [comment]
1) Endpoint su IPA a livello di AOO, mentre le PEC sembrano anche a livello di settore
Alcuni Enti hanno una struttura molto articolata di AOO e Settori sottostanti.
Prendiamo ad esempio Regione Piemonte con la AOO A1000A - DIREZIONE DELLA GIUNTA REGIONALE.
Tale AOO ha la sua PEC direzionegiunta@cert.regione.piemonte.it .
In questo momento però le trasmissioni di protocollo non sempre vengono inviate alla PEC dell'AOO, ma alle PEC del settore sottostante (ad es. regionali@cert.regione.piemonte.it).
Se abbiamo inteso correttamente l'allegato, in futuro tutto arriverà ad un unico endpoint della AOO. Come va interpretato il processo di smistamento sul settore? Potrebbe essere un valore contenuto nel messaggio stesso ad indicare il settore?

**RISPOSTA:** Assunto che per settori sottostanti si intendano le UO, ricordo che le comunicazioni tra gli enti sono realizzate tra AOO, infatti nell’IPA ogni UO è associata alla propria AOO

**Comment by vintra73** [comment]
2) Il nuovo protocollo di comunicazione tra AOO via web services prevede il riconoscimento delle due controparti: entrambe dovranno pubblicare il loro endpoint su IPA.
Nel processo attuale, con la PEC, due AOO che devono scambiarsi un documento non devono stipulare alcun accordo formale. Con la PEC non è previsto un riconoscimento delle due parti precedente allo scambio. Nel momento in cui si deve inviare un documento protocollato ad una AOO mai contattata in precedenza, viene indicato il suo indirizzo PEC.
Con il nuovo interscambio invece si prevede una sorta di accordo formale e di registrazione delle chiavi pubbliche del certificato affinché le due parti possano “colloquiare”:
L’instaurazione del canale dovrà essere fatta a seguito di una mutua autenticazione attraverso l’uso di certificati X509 V3 (tipicamente attraverso la verifica del campo subject DN dello stesso certificato). Le amministrazioni dovranno dotarsi dei certificati autonomamente
Dal punto di vista organizzativo questa nuova condizione potrebbe costituire uno scoglio. Come potrebbe essere mitigato l’impatto sull’Ente?

**RISPOSTA: Nell’allegato di indica l’utilizzo di certificati qualificati, che per loro natura garantiscono la certezza del soggetto a cui il certificato è stato rilasciato, nelle LG Sicurezza (in corso di emanazione) sono riportate gli OID e le modalità di valorizzazione per permettere di riscontrare automaticamente tramite la consultazione dell’IPA se il soggetto è una PA.**

**Comment by vintra73** [comment]
3) La Segnatura dovrà essere firmata attraverso Sigillo Elettronico qualificato (sia via PEC che sul canale WS-SOAP): se tale Sigillo fosse scaduto quando effettuo la verifica?
Se il Sigillo che garantisce l’integrità fosse valido nel momento in cui lo appongo (supponiamo in data odierna avvenga la protocollazione in uscita) ma l’AOO ricevente dovesse protocollare in ingresso tra un mese, quel Sigillo potrebbe non essere più valido.
Cosa posso fare al fine di non far scadere il Sigillo elettronico qualificato della mia AOO?
Nelle specifiche non abbiamo trovato riferimenti al momento in cui vada verificata la validità del sigillo sulla Segnatura. Crediamo sia da intendersi all'apposizione della stessa. Si parla genericamente di errore "001_ValidazioneFirma".
Dai wsdl vediamo che tale validazione è nella ResponseMessaggioInoltro, quindi sembrerebbe da intender-si valida alla data della trasmissione, non necessariamente a quella della protocollazione in ingresso a seguito della quale viene inviata la conferma. Se la trasmissione non fosse contestuale alla protocollazione in uscita (oggi protocollo e domani invio la segnatura, magari per tempi tecnici dell'ente) potrei comunque inviare una Segnatura con un Sigillo scaduto. Quali tipi di controlli dovrei applicare?
Quella degli allegati invece viene verificata in fase di conferma (006_DocumentoAllegatiErroreValidazioneSigillo) e a quel punto, il Sigillo potrebbe essere scaduto.

**RISPOSTA: Il controllo degli oggetti ricevuti è da realizzarsi in relazione al momento della firma, indicato negli element** *SegnaturaInformatica\Intestazione\Identificatore\DataRegistrazione* **e** *SegnaturaInformatica\Intestazione\Identificatore\OraRegistrazione*

**Comment by vintra73** [comment]
4) Cosa significa l'errore "000_Irricevibilita"?
Si tratta di un errore per processo interno dell'Ente? Un funzionario, dopo che il messaggio è arrivato correttamente ed ha passato i controlli formali, entra nel merito per protocollarlo e si accorge ad esempio che un allegato è in formato zip. Anche se tale formato è ammesso, il suo ufficio accetta solo pdf, quindi a quel punto rifiuta per irricevibilità e specifica di ritrasmettere il messaggio con il formato richiesto dal suo standard interno. È corretta questa interpretazione? L'errore di irricevibilità ci sembra avvenga dopo una serie di altri controlli.

**RISPOSTA: Ci si riferisce al riscontro che la Amministrazione ricevente effettua per determinare se quanto ricevuto è di propria competenza. In relazione ai formati si rimanda a quanto disposto dalle LG Documento Informatico.**

**Comment by vintra73** [comment]
5) Può verificarsi il caso in cui l’invio della Segnatura avvenga su canale a servizi e la conferma arrivi invece via PEC (o viceversa)?
La nostra AOO effettuerà una serie di tentativi di invio a servizi e poi, non riuscendoci, cambierà canale di trasmissione passando alla PEC per indisponibilità del primo. Il ricevente successivamente prova a contattarmi per la conferma e riesce a farlo sul canale prioritario. Oppure succede l’esatto opposto. La conferma potrebbe avvenire anche molto tempo dopo la trasmissione di protocollo (dalla documentazione si evince che il messaggio di conferma viene inviato solo quando l'AOO ricevente protocolla in ingresso).
Si può verificare questa condizione? I sistemi di invio e ricezione sono separati, potrebbe non essere raggiungibile uno mentre l’altro si. Deve essere fatto un controllo sul canale di trasmissione? Se ricevo il messaggio inoltro a servizi devo trasmettere necessariamente la conferma di ricezione del messaggio a servizi?

**RISPOSTA: Tale scenario non è previsto.**
