### ISSUE TITLE
Chiarimenti su applicazione linee guida in materia di interoperabilità

### ISSUE THREAD

**Issue by FilippoAntoni** [AgID/protocollo-comunicazione-aoo#14]
**Comunicazione tramite PEC : Messaggi di ritorno**
Vi chiediamo conferma che, in caso di utilizzo delle PEC come canale di comunicazione, i messaggi di ritorno rimangano invariati nelle caratteristiche di gestione e che pertanto le specifiche individuate nel paragrafo 3.1 dell'allegato 6 (Regole di processamento) siano da gestire al momento dell'utilizzo dei web services come canale di comunicazione (o comunque non siano da intendersi come adeguamenti vincolanti in caso di utilizzo delle PEC come canale di interoperabilità).

**Comunicazione tramite web services : ricevute con valore legale"**
Nello scenario di scambio di messaggi tra AOO tramite WebService (SOAP) si rileva la necessità di restituire al mittente (sistema chiamante) una ricevuta con valore legale dell’avvenuta consegna.

**Comment by vintra73** [comment]
In merito a **Comunicazione tramite PEC : Messaggi di ritorno** di rimanda a issue #12

In merito a **Comunicazione tramite web services : ricevute con valore legale** i messaggi scambiati, cosi come gli ack, sono firmati digitalmente dalle parti al fine di assicurarne l'integrità e no ripudiabilità.

**Comment by elisaleandri** [comment]
Non ci è chiara questa risposta: In merito a Comunicazione tramite web services : ricevute con valore legale i messaggi scambiati, cosi come gli ack, sono firmati digitalmente dalle parti al fine di assicurarne l'integrità e no ripudiabilità.
Cosa si intende? che debbano essere firmate le  requeste le response con un certificato di firma applicativo? Ci risulta che nell'allegato 6 si parli sono di firma della segnatura.

**Comment by vintra73** [comment]
@elisaleandri la ringrazio per la segnalazione.

Nella versione pubblicata si indicavano il profilo di iterazione “Bloccante RPC" e la "Soluzione per confidenzialità ed autenticazione del soggetto fruitore" per la tecnologia SOAP individuata nel modello di interoperabilità della PA (che allo stato risultava in pubblicazione).

Il fix-bug che stiamo realizzando ci permette di allineare il testo allo stato attuale, in quanto nel frattempo:

- è emanata la [Circolare 1/2000 dell'AgID](https://trasparenza.agid.gov.it/archivio28_provvedimenti-amministrativi_0_122346_725_1.html) recante le linea di indirizzo sulla interoperabilità tecnica
- è in essere la [consultazione del testo delle LG sull’interoperabilità tecnica delle Pubbliche Amministrazioni](https://docs.italia.it/italia/piano-triennale-ict/lg-modellointeroperabilita-docs/it/bozza/index.html)  per la loro adozione ai sensi dell'art. 71 del CAD 

Coglieremo la sua osservazione quale stimolo a migliorare il testo dell'allegato al fine di ridurre misunderstanding in merito.

Grazie

**Comment by franthemanIT** [comment]
Ci associamo alla "preoccupazione" circa il valore legale delle ricevute prodotte a seguito di comunicazioni via WS.
Le ricevute PEC, per legge, hanno pieno valore legale e sono opponibili a terzi, perché prodotte da un soggetto appositamente autorizzato e dotato di pubblica fede. 
Le ricevute WS, se anche firmate digitalmente, sono oggetti emessi dalle parti coinvolte nel processo e sembra che offrano una minore capacità probatoria.
Ci sono norme di legge, indicazioni o studi sul loro valore in caso di contenzioso?

**Comment by vintra73** [comment]
Buonasera, 
in merito si rimanda a quanto disposto all'articolo 35 del [Regolamento eIDAS](https://eur-lex.europa.eu/legal-content/IT/TXT/HTML/?uri=CELEX:32014R0910&from=IT#d1e2713-73-1).

**Comment by franthemanIT** [comment]
Buongiorno. 
L'art. 35 eIDAS risponde solo in parte alla questione, che - passando al linguaggio CAD - non riguarda a capacità dei messaggi con sigillo qualificato di "soddisfare il requisito della forma scritta", fatto che non era in discussione (anche se, per il valore documentale sarebbe necessario anche un riferimento temporale che, allo stato attuale, è una marca temporale, l'invio via pec, l'invio in conservazione oppure la marca postale).
Il punto è il valore erga omnes di quanto dichiarato nei messaggi: A dice di avere inviato a B  il messaggio X al tempo T1, B dice di aver ricevuto da A il messaggio X al tempo T2. Nei rapporti fra A e B tutto ciò fa fede fin tanto che uno dei due soggetti non mette in dubbio quanto detto dall'altro. Se è coinvolto un terzo soggetto C potrebbero nascere dei problemi, che non esistono nel mondo PEC vista la presenza del gestore PEC che certifica invio, consegna, contenuto e integrità del messaggio in modo opponibile a terzi (è il suo lavoro).
