### ISSUE TITLE
Dubbi emersi in fase di analisi per l'adeguamento della segnatura

### ISSUE THREAD

**Issue by FilippoAntoni** [AgID/protocollo-comunicazione-aoo#15]
Siamo a richiedere approfondimenti rispetto ad alcune situazioni riscontrate in fase di adeguamento alla nuova versione della segnatura.

1) Il destinatario è diventato un SoggettoType che può essere:
<xs:choice>	
	<xs:element name="Organizzazione" type="prot:OrganizzativaType"/>
	<xs:element name="Persona" type="prot:PersonaType"/> 
</xs:choice>

ovvero in alternativa Organizzazione o Persona
L'organizzazione è così definita
<xs:sequence>	
	<xs:element name="Riferimento" type="prot:NomeOrganizzazioneType"/>
	<xs:choice minOccurs="0">
	<xs:element name="UnitaOrganizzativa" type="prot:OrganizzativaType"/>
	<xs:element name="Persona" type="prot:PersonaType"/>
	</xs:choice>
</xs:sequence>
ovvero un riferimento ad un' "organizzazione" che è caratterizzata dal nome dell'organizzazione e, quando esiste, il codice IPA della stessa e opzionalmente unità organizzative o persone.

In pratica riscontriamo come sia scomparso il riferimento ad amministrazione e aoo: una sola delle due può essere referenziata e nel caso della aoo, il cui codiceIPA non è univoco, non ci permette di risalire al destinatario.
Non abbiamo inoltre trovato nemmeno alcun riferimento all'indirizzo telematico dei destinatari, rendendo in questo modo meno leggibile la segnatura.

2) sempre nei destinatari, in caso di destinatario che non sia una Amministrazione, è presente solo il tag Persona che ha obbligatori nome e cognome e facoltativo codice fiscale (con pattern specifico) ma non  partita iva (necessaria in caso di comunicazione di aziende).

3) nella produzione di un destinatario come persona, se si specifica l'indirizzo postale, abbiamo riscontrata l'obbligatorietà del codice istat del comune.

**Comment by vintra73** [comment]
si rimanda alla issue #6
