### ISSUE TITLE
Bug fix in progress, view branch fixbug-2021

### ISSUE THREAD

**Issue by vintra73** [AgID/protocollo-comunicazione-aoo#21]
Si segnale che è in realizzazione il bug fix sul branch https://github.com/AgID/protocollo-comunicazione-aoo/tree/fixbug-2021

**Comment by elisaleandri** [comment]
Stiamo verificando la segnatura e abbiamo riscontrato quanto segue:
- in DocumentoType è presente due volte l'elemento "sigillatoElettronicamente", forse un elemento dovrebbe essere "marcaturaTemporale"?
- l'elemento "CFPA" contento all'interno del tipo "AmministrazioneType" è di tipo "CodiceFiscaleType", ma tale tipologia sembra essere compatibile solo con i CF di persone fisiche. Ad esempio il CF del Comune di pisa è 00341620508, quindi un formato non compatibile con quello richiesto in "CodiceFiscaleType".

**Comment by vintra73** [comment]
@elisaleandri la ringrazio per le osservazioni, abbiamo provveduto ad effettuare fixing di quanto segnalato.
