### ISSUE TITLE
Messaggi di grande dimensione

### ISSUE THREAD

**Issue by franthemanIT** [AgID/protocollo-comunicazione-aoo#34]
Buongiorno,
come p.a., il Comune di rivoli rappresenta un caso concreto e quotidiano.
Invio di una comunicazione protocollata con queste caratteristiche:
- 31 allegati;
- dimensione complessiva 105MB
- 18 destinatari fra cui: 10 p.a., 5 grandi società, 1 società partecipata, 2 professionisti (privati).

Nello specifico si tratta di una comunicazione riguardante un "piano esecutivo convenzionato" che per sua natura riguarda più soggetti di varia natura e lo scambio di elaborati e progetti di dimensioni elevate e in quantità elevata.

Riallacciandoci a varie issue aperte, non ci sembra di vedere nelle nuove linee guida una soluzione univoca a questa esigenza, sicuramente comune a qualsiasi p.a.

Al momento tutte le soluzioni che si possono mettere in campo sono soluzioni particolari, spesso di compromesso e in deroga alla normativa e alle buone pratiche archivistiche, e soprattutto non condivise da tutte le p.a. e non esperibili verso società o professionisti privati Fra queste:
- suddivisione della comunicazione in più invii PEC e quindi in più registrazioni di protocollo: errore archivistico e aggravio di procedura per mittente e destinatario;
- messa a disposizione dei file su server esterno eventualmente protetto da password: altro errore archivistico perche' il protocollo  del mittente non acquisisce i documenti e chi riceve non ha garanzia sulla immodificabilità / non sostituzione del file. onerosità e rischio per la sicurezza per il destinatario,
con eventuali varianti sul tema.

Nel caso specifico, avendo il Comune messo a disposizione i file su un proprio server, un ente pubblico ha rifiutato la comunicazione rispondendo nel seguente, condivisibile, modo: "per ragioni di sicurezza e ai fini della conservazione agli atti dell'archivio della documentazione inviata, ci vediamo costretti a non accettare la ricezione di documenti salvai su server esterni. Gli allegati devono essere inseriti fisicamente nella PEC".

Come accennato, nemmeno le nuove linee guida consentono l'individuazione di una modalità unica e condivisa per lo scambio di messaggi voluminosi. Se l'ipotesi WS SOAP potrebbe - nn in tempi brevi - risolvere la questione per comunicazioni fra AOO, il problema resta immutato per destinatari di altra natura giuridica che, come nel caso concreto descritto, possono essere destinatari di una comunicazione inviata anche a p.a. 

La mancanza di una modalità unica per gestire queste situazioni rende di fatto impossibile la realizzazione di qualsiasi strumento per automatizzare l'invio di comunicazione voluminose: potremmo chiedere alla software house che ci fornisce il protocollo informatico una modifica che soddisfi le nostre esigenze di mittente ma che potrebbe continuare a produrre comunicazioni che un destinatario può rifiutare o non essere in grado di interpretare. Nel verso opposto, quando siamo destinatari, non possiamo far implementare alcun meccanismo per interpretare invii voluminosi, perché non esiste un modo unico.

Forse i tempi sono maturi per una soluzione unica e condivisa, che guardi anche al di là del panorama AOO?

**Comment by vintra73** [comment]
@franthemanIT in merito al dubbio espresso la invitiamo a consultare il bx-bug realizzato e disponibile all'URL https://github.com/AgID/protocollo-comunicazione-aoo/tree/fixbug-2021, nello specifico l'introduzione dell'element CollocazioneTelematica tipizzato:

...
        <xs:complexType name="CollocazioneTelematicaType">			
		<xs:sequence>
			<xs:element name="HostValue" type="xs:anyURI"/>
			<xs:element name="PathValue" type="xs:anyURI"/>
		</xs:sequence>
		<xs:attribute name="timeToLive" type="xs:integer" />				
		<xs:attribute name="userId" type="xs:string"/>
		<xs:attribute name="password " type="xs:string"/>
	</xs:complexType>
...

**Comment by franthemanIT** [comment]
Grazie, a partire dal redivivo elemento CollocazioneTelematica, avrei elaborato alcune implementazioni di conseguenza, che potrebbero risolvere del tutto il problema dei messaggi pesanti anche per comunicazioni che coinvolgono terminali non AOO.
Sa indicarmi un luogo dove condividere il risultato dell'analisi? (A occhio, con le dovute revisioni, potrebbe trovare spazio nelle linee guida come requisito funzionale minimo di un sistema di gestione informatica dei documenti o protocollo informatico che dir si voglia).
