### ISSUE TITLE
Apertura consultazione Linee Guida Tecnologie e standard per la sicurezza dell’interoperabilità tramite API dei sistemi informatici

### ISSUE THREAD

**Issue by elisaleandri** [AgID/protocollo-comunicazione-aoo#35]
A fronte della pubblicazione in consultazione delle "Linee Guida Tecnologie e standard per la sicurezza dell’interoperabilità tramite API dei sistemi informatici" (https://www.agid.gov.it/it/agenzia/stampa-e-comunicazione/notizie/2021/04/19/api-consultazione-linee-guida) ci sembra che le specifiche per riuscire a implementare correttamente le interfacce di servizio SOAP dell'Allegato 6 siano ancora "non definitive".
In questo quadro come si inserisce la scadenza di giugno? 
Non ritenete che nello scenario sopra descritto l'unico cosa "certa" rimane lo scambio di messaggi tramite PEC? Che invece avevamo capito dover essere residuale rispetto ai servizi.

**Comment by vintra73** [comment]
Buonasera, in merito alle LG da lei indicate non ci è chiaro cosa renda non applicabile quanto previsto nell'allegato 6, in relazione alle LG da lei indicate non si rileva nessuna contradizione considerato:
- gli standard utilizzati per l'implementazione dei WS sono inclusi delle indicate LG, ed ancor più i pattern adottati sono coerenti a quanto indicate nelle ["linea di indirizzo sulla interoperabilità tecnica" adottate con Determinazione n. 406/2020 ](https://trasparenza.agid.gov.it/archivio28_provvedimenti-amministrativi_0_122346_725_1.html)
- la costituzione del trust corrisponde a quanto indicato nelle indicate LG relativamente ai "[Certificati digitali emessi da CAQ eIDAS"](https://docs.italia.it/AgID/documenti-in-consultazione/lg-sicurezza-interoperabilita-docs/it/bozza/doc/00_Linee%20guida%20sicurezza%20API/07_construzione-trust/02_emissione_distribuzione_certificati_digitali/01_certificati_eIDAS.html) in coerenza con quanto indicato in ["Principi per la scelta delle modalità di emissione dei certificati digitali"](https://docs.italia.it/AgID/documenti-in-consultazione/lg-sicurezza-interoperabilita-docs/it/bozza/doc/00_Linee%20guida%20sicurezza%20API/07_construzione-trust/02_emissione_distribuzione_certificati_digitali/03_scelta_modalita_emissione_certificati.html) delle stesse LG

Restiamo a diposizione per ulteriori chiarimenti
