### ISSUE TITLE
Versione definitiva della Segnatura_protocollo.xsd da utilizzare

### ISSUE THREAD

**Issue by alessandra-211177** [AgID/protocollo-comunicazione-aoo#36]
Buongiorno,
abbiamo la necessità di sapere qual'è la versione definitiva della Segnatura da utilizzare per gli sviluppi.
Dal 07 giugno stando alla Normativa, riceveremo la segnatura nel nuovo formato, che però ad oggi non è ancora completamente definito.

**Quale formato di segnatura_protocollo.xsd è da considerarsi quella da utilizzare?**

La versione sul ramo master è di settembre 2020,
quella del ramo bug-fix, che abbiamo concordato di usare nell'incontro con voi, è ora modificata e non è ancora stata
ufficializzata.

Abbiamo visto comparire una precisazione sul codice aoo nell'identificativo della segnatura:
--> codiceAOO, il codice IPA dell'AOO (attributo cod_uni_aoo dell’entità AOO dell’IPA)
Questo ci crea un po' di problemi perchè nella precedente Segnatura da Circolare 60 il codiceAOO non era il nuovo codice univoco aoo di 7 caratteri definito da IPA nelle recenti comunicazioni (la modifica comporterebbe ulteriori valutazioni perchè non è riconducibile a quanto avveniva in passato).

Abbiamo anche altre necessità da chiarire:
- il codice fiscale / p.iva della PG, nella versione da cui siamo partiti era in alternativa.
Abbiamo progettato la nostra base dati per recepire entrambi i valori mentre ora sono stati accorpati e non capiamo come distinguerli.
- è comparso l'elemento AmministrazioneEstera che non avevamo previsto di gestire. 
  
Ogni change per noi comporta delle modifiche. 

Per rispettare le scadenze di giugno potreste darci la data di pubblicazione definitiva, nella quale il ramo bug-fix 
diverà master?

Sarebbe inoltre possibile indicare un numero di versione differente sulla versione master e sulle versioni che si susseguono in bug-fix per poter anche a posteriori identificare versioni di segnatura differenti dalla corrente ma che, in un momento storico, sono state per così dire ufficiali?
Ci potrebbe tornare utile per identificare ora e a tendere le variazioni.

Cordiali Saluti

**Comment by vintra73** [comment]
buongiorno @alessandra-211177 , in merito alle tue:

1. maggiori dettagli sul processo amministrativo in merito alla ufficializzazione dell'errata corrige di quanto riportato in https://github.com/AgID/protocollo-comunicazione-aoo/tree/fixbug-2021 se ne sta occupando la dott.sa Patrizia Gentili

2. In merito al codice AOO da utilizzare ci siamo coordinati con i referti interne di Indice PA, trovi sempre sul https://github.com/AgID/protocollo-comunicazione-aoo/tree/fixbug-2021 le correzioni conseguenti e, colgo l'occasione per anticiparti, che il dataset https://indicepa.gov.it/ipa-dati/dataset/aree-organizzative-omogenee includerà anche il riferimento a cod_aoo per gestire la transazione al Codice_uni_aoo

3. le modifiche che segnali in relazione a "codice fiscale / p.iva" e AmministrazioneEstera derivano dall'allineamento con l'allegato 5, per maggiori informazioni ti chiedo di contattare  la dott.sa Patrizia Gentili

4. in relazione al versioning delle versioni reputiamo non necessario in quanto l'errata corrige, di cui al punto 1, non rappresenta una nuova versione ma una correzione della precedente, assumendo non utilizzabile quest'ultima
