### ISSUE TITLE
Allegato 6 - Dubbi - Schema XSD PEC protocollo di comunicazione

### ISSUE THREAD

**Issue by servizidigitali** [AgID/protocollo-comunicazione-aoo#37]
Buongiorno

leggendo l'allegato 6 delle linee guida sulla formazione, gestione e conservazione non mi sono chiari i seguenti aspetti:

il nuovo schema XSD per la segnatura (appendice A dell'allegato 6) si utilizzerà solo per l’utilizzo dei WS SOAP?
Nel periodo transitorio invece, in attesa che tutte le AOO provvedono ad attrezzarsi con gli opportuni strumenti per l’utilizzo dei WS SOAP, si continuerà ad utilizzare la modalità di comunicazione tramite posta elettronica certificata (PEC)  con lo schema  XSD previsto dalla Circolare AgID 60/2013?

Grazie
Cordiali saluti

**Comment by vintra73** [comment]
@servizidigitali in merito hai suoi dubbi abbiamo effettuato fix-bug in cui abbiamo, tra le altre, chiarito gli stessi

può consultare il tutto all'URL https://github.com/AgID/protocollo-comunicazione-aoo/tree/fixbug-2021

**Comment by jackom83** [comment]
Si conferma cosi come indicato nell'[Allegato 6 alle “Linee Guida sulla formazione, gestione e
conservazione dei documenti informatici"](https://www.agid.gov.it/sites/default/files/repository_files/all.6_comunicazione_tra_aoo_di_documenti_amministrativi_protocollati.pdf) che indipendentemente dal canale di trasporto (WS o PEC) lo schema delle segnatura da utilizzare è quello previsto nello allegato stesso
