### ISSUE TITLE
Dubbi sull'applicabilità del sistema di interoperabilità

### ISSUE THREAD

**Issue by atumino73** [AgID/protocollo-comunicazione-aoo#43]
Buongiorno,
scrivo in qualità di analista di un  sistema di protocollo informatico e  gestione documentale, distribuito su più di 3000 scuole. In fase di analisi e sviluppo  sono emerse una serie di criticità relativi alla gestione dell’intero flusso di comunicazione: in particolar modo il non avere garanzia della correttezza delle implementazioni effettuate dal sistema mittente e dal sistema ricevente, aggrava la complessità del processo con ripercussioni sia sul provider del  servizio che sull’utenza (operatori del servizi amministrativi delle pp.aa), di fatto costretti a monitorare due canali (pec/domicilio digitale e il sistema ws di interoperabilità).
Desideravamo sapere se è in previsione (ed eventualmente con quali tempistiche):
- un ambiente di test 
- verifica tecnica  da parte dell’AgID della correttezza delle implementazioni e validazione degli endpoint registrati nell’IPA
- percorso di certificazione dell’implementazione

Riguardo poi al sigillo elettronico, si prevedono delle convenzioni per l’acquisto da parte delle pubbliche amministrazioni con i fornitori qualificati?
Nel caso di messaggio protocollato inviato per pec istituzionale, c’è comunque obbligo di firma del file di segnatura con sigillo elettronico? 
La pec, se indicata peraltro come domicilio digitale, non dovrebbe garantire origine e integrità del messaggio, rendendo superflua la sottoscrizione con sigillo elettronico?
Per ultimo, desideravamo sapere se è prevista (e con quali tempistiche) l’implementazione di servizi rest in sostituzione dei soap

Cordialmente

**Comment by vintra73** [comment]
In merito ai quesiti posti di seguito le risposte agli stessi.

1. Disponibilità ambiente di test: non è previsto un ambiente di test

2. Verifica tecnica da parte dell'AgID: non è previsto nessuna veridica da parte di AgID, si assume il rispetto delle specifiche indicate nell'allegato in oggetto

3. Percorso di certificazione: vale quanto al punto 2

4. Convenzioni sigillo elettronico eIDAS:  non sono previste specifiche convenzioni, le PA si dotano del sigillo elettronico eIDAS utilizzando i normali strumenti di acquisto 

5. Inoltro tramite PEC: la formazione del file di segnatura deve rispettare quanto indicato nell'allegato in oggetto e nello specifico  quando indicato al capitolo 2 in merito alla formazione della segnatura e all'associazione permanente di questa e i documenti oggetto del messaggio protocollato (documento principale e allegati)

6. Garanzie della PEC: in merito si ricordo che l'apposizione del sigillo è indicata come soluzione per assicurare l'associazione permanente tra la segnatura e i documenti oggetti del messaggio protocollato (documento principale e allegati)

7. L'implementazione dei servizi utilizzando la tecnologia REST, conformemente alle LG Interoperabilità tecnica (vedi https://docs.italia.it/italia/piano-triennale-ict/lg-modellointeroperabilita-docs/it/bozza/index.html), è prevista come evoluzione dei prossimi aggiornamenti dell'allegato in oggetto

**Comment by franthemanIT** [comment]
Mi scuso ma relativamente al punto 2, non si potrebbe prevedere internamento a IPA o altrove, anche non vincolante un servizio, anche non vincolante, al quale un ente invia una comunicazione e ha in ritorno un check di validità della segnatura? Altrimenti non se ne esce...
