### ISSUE TITLE
Dubbi su Appendice C, Comunicazione tra AOO di Documenti Amministrativi Protocollati

### ISSUE THREAD

**Issue by RigSte** [AgID/protocollo-comunicazione-aoo#44]
Salve,

nell'Appendice C del documento in oggetto si fa riferimento ai nomi dei file degli allegati delle mail interoperabili (es.: Segnatura.xml, Aggiornamento.xml, etc.). I nomi dei file indicati hanno un carattere di obbligatorietà, o quella è solo un'indicazione facoltativa? Quello che fa fede, quindi, per riconoscere la tipologia del messaggio interoperabile è sempre la l'elemento root dell'xml, o si può fare affidamento anche al nome dell'allegato? Ad esempio, è consentito che l'allegato di segnatura si possa chiamare SegnaturaInformatica.xml (o in altro modo) invece di Segnatura.xml? 

Grazie

**Comment by vintra73** [comment]
In merito ai quesiti posti di seguito le risposte agli stessi:

1. i nomi dei file hanno carattere di obbligatorietà, è preservato il naming delle precedente disposizioni

2. il nome del file è utilizzato per le verifiche di completezza dell'inoltro, di contro l'elemento root xml dei singoli file è utilizzato per le verifiche di correttezza degli stessi

3. no, vale quanto indicato in precedenza
