### ISSUE TITLE
Dubbio invio conferma in caso di anomalia

### ISSUE THREAD

**Issue by asorcinelli** [AgID/protocollo-comunicazione-aoo#46]
Salve,
avrei bisogno di qualche chiarimento relativamente all'invio della conferma e in particolare quando il destinatario deve segnalare un'anomalia. Il WSDL prevede che per il metodo **ConfermaMessaggioInoltro** si debba restituire l'identificatore del mittente e, nel caso di anomalia, il parametro Anomalia di tipo **AnomalieConfermaType**.
Nell'ipotesi di avere un mittente che invia ad un destinatario, il discorso è chiaro e non ci sono problemi. I miei dubbi nascono nel caso in cui un mittenti invii a più destinatari e successivamente riceva delle anomalie. Chiaramente nella situazione ideale se il messaggio inviato ha qualche errore, tutti i destinatari dovrebbero inviare la medesima anomalia.
Però nella realtà ci sono sistemi diversi, implementati in modo diverso ed è possibile che solo alcuni destinatari restituiscano l'anomalia (è già capitato in passato che qualche sistema non riconoscesse come valide delle segnature corrette).
In questi casi, dato che la comunicazione della conferma è ascinrona, il mittente si troverebbe con diverse chiamate al metodo **ConfermaMessaggioInoltro**, ma non riuscirebbe a capire da chi arriva una certa anomalia perchè il metodo consente solo di specificare l'identificatore del mittente e l'anomalia. Nell'oggetto **AnomalieConfermaType** però non c'e' la possibilità di specificare il codice IPA del destinatario che sta inviando il messaggio e quindi il risultato è che il mittente riceve N anomalie, ma non sa da chi sono state inviate.
Se invece le conferme arrivano correttamente, allora al posto dell'anomalia il mittente riceve l'identificatore del destinatario e quindi riesce a capire da chi arriva il messaggio.

Come va gestita questa situazione? E' prevista qualche modifica in questo metodo?

**Comment by jackom83** [comment]
Salve, partendo dal presupposto che un eventuale comunicazione 1:N, a livello SOAP, corrisponde nel modello dato a N comunicazioni 1:1 l'informazione della sorgente del messaggio è presente nel certificato associato al materiale crittografico con cui si garantiscono le caratteristiche di sicurezza dello scambio (la firma del payload soap, vedi profilo [INTEGRITY_SOAP_01]), grazie all'inclusione nello stesso degli OID 2.5.4.97 e 2.5.4.11 come previsto dalle "Linee Guida Tecnologie e standard per la sicurezza dell’interoperabilità tramite API dei sistemi informatici"

**Comment by asorcinelli** [comment]
Capisco ed è tutto giusto. A livello tecnico, almeno per le librerie che utilizziamo, non è proprio agevole andarsi a recuperare questo informazioni che sono a basso livello, sono presenti solo a livello di "trasporto" del messaggio.
Speravo si potesse fare come in tutti gli altri casi dove questa informazione è presente. Del resto è sempre vero che ci sono nel certificato dato che tutti i messaggi vengono firmati.
Comunque grazie per il chiarimento.
