### ISSUE TITLE
Segnatura, sigillo e invio tramite web service

### ISSUE THREAD

**Issue by asorcinelli** [AgID/protocollo-comunicazione-aoo#47]
Salve,
avrei dei dubbi sulla generazione della segnatura, sull'applicazione del sigillo e sul successivo invio tramite web service.
La generazione della segnatura in base alle specifiche dell'XSD e l'applicazione del sigillo non sono un problema. Ottengo una cosa di questo tipo:

```
<?xml version="1.0" encoding="utf-8"?>
<prot:SegnaturaInformatica xmlns:prot="http://www.agid.gov.it/protocollo/" prot:versione="3.0.0" prot:lang="it">
  <prot:Intestazione>
    <prot:Identificatore>
     ....
    </prot:Identificatore>
    <prot:Oggetto>Oggetto</prot:Oggetto>
    <prot:Classifica>
      ....
    </prot:Classifica>
  </prot:Intestazione>
  <prot:Descrizione>
    <prot:Mittente>
      ...
    </prot:Mittente>
    <prot:Destinatario>
      ...
    </prot:Destinatario>
    <prot:DocumentoPrimario prot:nomeFile="DOCUMENTO" prot:mimeType="application/pdf">
      ...
    </prot:DocumentoPrimario>
  </prot:Descrizione><ds:Signature xmlns:ds="http://www.w3.org/2000/09/xmldsig#" Id="Signature-334305326">
	....
</ds:Signature>
</prot:SegnaturaInformatica>
```

La successiva validazione tramite XSD va a buon fine e anche la validazione del sigillo viene verificata senza errori.
Quello che mi risulta problematico è l'invio tramite web service. In modo particolare analizzando il WSDL quello che vedo è che il messaggio SOAP relativo alla richiesta di inoltro dovrebbe essere una cosa di questo tipo:

```
<s:Envelope xmlns:a="http://www.w3.org/2005/08/addressing" xmlns:s="http://www.w3.org/2003/05/soap-envelope">
  <s:Header>
    <a:Action s:mustUnderstand="1">http://tempuri.org/IProtocolloDestinatario/MessaggioInoltro</a:Action>
    <a:MessageID>urn:uuid:9247cadd-5334-4fb0-ae0c-e78f16dd29ce</a:MessageID>
    <a:ReplyTo>
      <a:Address>http://www.w3.org/2005/08/addressing/anonymous</a:Address>
    </a:ReplyTo>
  </s:Header>
  <s:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
    <MessaggioInoltro xmlns="http://tempuri.org/">
      ﻿<Segnatura xmlns:prot="http://www.agid.gov.it/protocollo/" prot:versione="3.0.0" prot:lang="it">
                <prot:Intestazione>
		  .....
		 </prot:Intestazione>
 		  .....
		  <ds:Signature Id="ID" xmlns="http://www.w3.org/2000/09/xmldsig#">
		  .....
		  </ds:Signature>
	  </Segnatura>
      <files>
        <FileType nomeFile="FILE1">CONTENT</FileType>
      </files>
    </MessaggioInoltro>
  </s:Body>
</s:Envelope>
```
L'elemento Segnatura è di tipo **SegnaturaInformaticaType** e quindi è dello stesso tipo che ho utilizzato per la generazione della segnatura del mittente. Il problema è che il nodo root risultante viene chiamato "Segnatura" e non "SegnaturaInformatica". 
Quindi per generare un messaggio SOAP di questo tipo devo prendere la segnatura originale e cambiare il nome del nodo root. Questa modifica però implica che il sigillo non sarà più valido e devo applicarne un altro.
Anche se applicassi un nuovo sigillo, in ogni caso il destinatario riceverebbe una segnatura diversa rispetto a quella del mittente.

In conclusione quello che mi chiedo è:

1) Non sarebbe meglio passare la segnatura come **FileType** come si per gli altri allegati? Sarebbe un po' tornare alla situazione delle email in cui la segnatura è un semplice allegato di una email, che poi dovrà avere una certa struttura definita dall'apposito XSD.
2) Nel caso in cui non sia possibile il discorso del **FileType**, non sarebbe almeno possibile allineare i nomi degli elementi della segnatura?

Sto sbagliando qualcosa su quanto ho detto in precedenza?

**Comment by jackom83** [comment]
Salve, Il fatto che nello schema XSD "segnatura_protocollo.xsd" sia dichiarato un element con name "SegnaturaInformatica" di tipo "SegnaturaInformaticaType", non impedisce di generare documenti XML contenenti element con name diversi (es. "Segnatura") di tipo "SegnaturaInformaticaType" è di effettuare la validazione rispetto allo schema relativo. 

Riprendendo il suo esempio avrebbe una cosa del tipo seguente

    <Segnatura prot:lang="it" prot:versione="3.0.0" 
           xmlns:prot="http://www.agid.gov.it/protocollo/" 
           xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" 
           xsi:type="prot:SegnaturaInformaticaType" >
    
         <prot:Intestazione>
    		    .....
    	</prot:Intestazione>
     		     .....
         <ds:Signature Id="ID" xmlns="http://www.w3.org/2000/09/xmldsig#">
    		     .....
         </ds:Signature>
    </Segnatura>
 e di conseguenza nel pacchetto soap 
```
<soap:Envelope xmlns:soap="http://www.w3.org/2003/05/soap-envelope">
  <soap:Header>
	.....
  </soap:Header>  
  <soap:Body xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance" xmlns:xsd="http://www.w3.org/2001/XMLSchema">
   <MessaggioInoltro xmlns="http://tempuri.org/">
     ﻿<Segnatura prot:versione="3.0.0" prot:lang="it"
	   ﻿xmlns:prot="http://www.agid.gov.it/protocollo/"
	   ﻿xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
	   ﻿xsi:type="prot:SegnaturaInformaticaType" >
           
        <prot:Intestazione>
    		    .....
    	</prot:Intestazione>
     		     .....
         <ds:Signature Id="ID" xmlns="http://www.w3.org/2000/09/xmldsig#">
    		     .....
         </ds:Signature>
     </Segnatura>
     ...
   </MessaggioInoltro>
  </soap:Body>
</soap:Envelope>
```


```

**Comment by asorcinelli** [comment]
Si è vero. Mi preoccupa solo il fatto di una validazione fatta da terzi tramite l'XSD in cui non si abbia questa "flessibilità".
Ci sono già capitate situazioni simili in passato e una differenza come questa produceva rifiuti dei messaggi. Non vorremmo tornare ad una situazione simile.

Comunque al momento farò come mi ha suggerito che penso sia la soluzione più lineare e semplice.
Grazie.

**Comment by elisaleandri** [comment]
Scusate, non ho dubbio che la soluzione proposta sia valida dal punto di vista tecnico, ma non è dal punto di vista giuridico.
Se si segue la strada indicare da @jackom83 a mio avviso ci possono essere problemi di validazione della segnatura da parte del destinatario.
Questo se valida la segnatura secondo l'XSD di AGID avrà un errore e la segnatura risulterà non valida.
Secondo quale schema a suo avviso il destinatario dovrebbe validare la segnatura per non avere errori?
La validazione non dovrebbe essere fatta esclusivamente utilizzando l'XSD AIGID?
Seguendo questa linea il mittente potrebbe indicare qualsiasi cosa nell'element root...
Inoltre nel caso in cui la mia comunicazione deve essere inviata a un destinatario PEC e uno servizi sarei costretta a generare due segnature diverse, uno con il nome segnatura e una con segnatura informatica.

**Comment by asorcinelli** [comment]
Anche io ero dubbioso, come da miei commenti precedenti.
Però effettivamente se si indica il tag "xsi:type="prot:SegnaturaInformaticaType"" a questo punto la validazione tramite XSD viene eseguita correttamente.
Sostanzialmente è vero che l'elemento root può chiamarsi in qualsiasi modo, ma specificando il tipo si fa ricondurre tutto a quanto specificato nell'XSD e la validazione non da più errori.
Quello che può accadere (che a noi è già accaduto..) è che il sistema che riceve quando elabora la segnatura, dovrà gestire il nodo root in modo "dinamico" e non dovrà "pensare" che il suo nome sia sempre e comunque "SegnaturaInformatica".

**Comment by elisaleandri** [comment]
Quello proposto rimane un "trucco tecnico".  Rimane la questione che per AGID la segnatura dovrebbe chiamarsi segnatura informatica per la PEC e segnatura per i servizi.
Tecnicamente possiamo trovare tutti i barbatrucchi del mondo, ma a livello giuridico credo che sia fondamentale trovare univocità nella nomenclatura di un file così rilevante a livello amministrativo.
Sarebbe gradita una risposta da AIGID (@vintra73) che chiarisca il tutto.

**Comment by asorcinelli** [comment]
Si su questo sono d'accordo, anche perchè di trucchi tecnici poi ce ne sono altri in cascata che si sarebbero potuti evitare avendo una univocità nella nomenclatura.
