### ISSUE TITLE
Chiarimento voce di classifica in segnatura

### ISSUE THREAD

**Issue by elisaleandri** [AgID/protocollo-comunicazione-aoo#48]
Analizzando la segnatura ci risulta che è possibile indicare un solo valore di classifica, nella vecchia era invece una lista.
A livello archivistico questo non è corretto in quanto un protocollo può avere più classifiche.
Questo ci sembra una discreta limitazione anche poi  per la fase di fascicolazione.

**Comment by jackom83** [comment]
Dalle analisi realizzate dal Tavolo di lavoro dell’Agenzia per l’Italia Digitale, istituito con determinazione del Direttore Generale n. 137 del 2 maggio 2018, sentito anche il MIC come da art. 23 ter comma 4 del CAD è scaturita l’evidenza in merito alla cardinalità della classificazione. 

A conferma di ciò si evidenza che relativamente alla cardinalità della classificazione, equivalente scelta è stata assunta anche nell’[allegato 5  “I metadati”](https://www.agid.gov.it/sites/default/files/repository_files/all.5_metadati.pdf). 

Considerando che l’indicazione da lei fornita ha impatto non solo per le specifiche tecniche dell’[Allegato 6 “Comunicazione tra AOO di Documenti Amministrativi Protocollati”](https://www.agid.gov.it/sites/default/files/repository_files/all.6_comunicazione_tra_aoo_di_documenti_amministrativi_protocollati.pdf) contenute nel presente repo, ma più in generale sull’intera [“Linee Guida sulla formazione, gestione e conservazione dei documenti informatici”](https://www.agid.gov.it/sites/default/files/repository_files/linee_guida_sul_documento_informatico.pdf) , la invitiamo a prendere visione delle FAQ presenti all’URL [https://www.agid.gov.it/it/domande-frequenti/documento-informatico](https://www.agid.gov.it/it/domande-frequenti/documento-informatico) ed in caso di necessità di chiarimenti ulteriori procedere nei modi indicati allo stesso URL.
