### ISSUE TITLE
Codice AOO vs Codice_uni_aoo

### ISSUE THREAD

**Issue by elisaleandri** [AgID/protocollo-comunicazione-aoo#49]
Cosa si intende in segnatura per "CodiceAOO"?
Il "vecchio"codice AOO che è sempre stato presente in IPA oppure quello che adesso viene definito in IPA Codice_uni_aoo?

Esempio Regione Toscana Giunta:
Codice AOO: AOOGRT
Codice_uni_aoo: A03E926

Nell'attuale segnatura è sempre stato indicato il codice AOO che poi nei software di protocollo deve essere associato al registro di protocollo?

**Comment by jackom83** [comment]
In relazione alle sua richiesta si ricorda che il contenuto del presente repo afferisce alle specifiche tecniche di cui all’[allegato 6 “Comunicazione tra AOO di Documenti Amministrativi Protocollati”](https://www.agid.gov.it/sites/default/files/repository_files/all.6_comunicazione_tra_aoo_di_documenti_amministrativi_protocollati.pdf) delle [“Linee Guida sulla formazione, gestione e conservazione dei documenti informatici”](https://www.agid.gov.it/sites/default/files/repository_files/linee_guida_sul_documento_informatico.pdf)   in cui alla nota presente alla pagina 7 si chiariscono le regole di popolamento dell’element **CodiceAOO**.
