### ISSUE TITLE
Link WebService su IndicePA

### ISSUE THREAD

**Issue by servizidigitali** [AgID/protocollo-comunicazione-aoo#50]
Buongiorno,
in prospettiva di dover aggiornare il link webservice della propria AOO e di conseguenza anche reperire quelli delle altre PA, ci sarà una nuova sezione su IndicePa da compilare? Ora non compare ancora nulla

**Comment by jackom83** [comment]
In relazione alle sua richiesta si ricorda che il contenuto del presente repo afferisce alle specifiche tecniche di cui all’[allegato 6 “Comunicazione tra AOO di Documenti Amministrativi Protocollati”](https://www.agid.gov.it/sites/default/files/repository_files/all.6_comunicazione_tra_aoo_di_documenti_amministrativi_protocollati.pdf) delle [“Linee Guida sulla formazione, gestione e conservazione dei documenti informatici”](https://www.agid.gov.it/sites/default/files/repository_files/linee_guida_sul_documento_informatico.pdf), in cui sono esplicitate informazioni aggiuntive utili all’implementazione delle stesse specifiche ed in particolare, relativamente alla sua, si conferma che nell’IndiceIPA è possibile registrare per le AOO l’attributo **URI_Protocollo_informatico** come indicato alla pagina 27 dell’allegato 6.
