### ISSUE TITLE
Casi di segnature ricevute senza dati obbligatori - impronta non corrispondente e ditte individuali

### ISSUE THREAD

**Issue by alessandra-211177** [AgID/protocollo-comunicazione-aoo#51]
Buongiorno, riepiloghiamo alcune problematiche riscontrate con Segnature nel formato NLG - Allegato 6.

1)  Alcuni Enti ci inviano delle Segnature di Protocollo nel nuovo formato senza valorizzare alcuni dati obbligatori (ad es. uno spazio nel codice dell'AOO).
Il nostro sistema non aveva previsto tale "anomalia" e quindi ci stiamo predisponendo ad aggirarlo incanalando il messaggio in un percorso differente: lo presenteremo all'Ente come una PEC senza la segnatura. Da questo processo si può comunque fare una protocollazione "assistita" ma l'operazione per l'Ente destinatario è molto più macchinosa.
Non possiamo applicare un controllo bloccante perché l'xsd permette di introdurre tale dato sporco; caso diverso sarebbe se l'xsd non permettesse di mettere nei dati obbligatori spazi o valori vuoti: questo obbligherebbe il mittente a formare bene il messaggio prima di inviarlo.

Tale anomalia spesso maschera altri errori: se il codice aoo viene valorizzato con una stringa vuota, non riusciamo nemmeno a mandare la notifica di eccezione al mittente se necessaria.
Lasciandolo passare non segnaleremo più nulla al mittente, ed esso continuerà ad utilizzare lo stesso tracciato errato. Ci chiedevamo se altri vi hanno segnalato il problema e se come AgiD pensate di sopperire gestendo la possibilità di risposta in caso di assenza di un dato obbligatorio o se pensate di irrobustire lo schema non permettendo l'introduzione di queste casistiche.

Ci avete segnalato la issue https://github.com/AgID/protocollo-comunicazione-aoo/issues/45 in cui sono posti temi assimilabili e da cui si evince che un caso del genere (assenza del codice univoco aoo) dovrebbe costituire un rifiuto automatico con notifica di eccezione. E' corretta l'interpretazione?

2) Un' altra casistica riscontrata riguarda la difficoltà di introdurre dei soggetti PG di tipo ditta Individuale all'interno della Segnatura di protocollo.
Per la persona giuridica è previsto questo:
```
<xs:complexType name="PersonaGiuridicaType">
<xs:sequence>
<xs:element name="Denominazione" type="xs:string"/>
<xs:element name="PIVAoCF" type="prot:PartitaIVA" minOccurs="0"/>
```

dove però il tipo PartitaIVA è sempre lungo 11 e va bene sia per p.iva di una persona giuridica che per cf degli Enti -->es. Regione Piemonte 80087670016.

Nel caso della ditta individuale invece il codice fiscale, che la identifica univocamente, è quello del titolare (quindi un alfanumerico di 16). In alcuni casi ci viene passato solo il CF e non la partita IVA, ma nella Segnatura non possiamo introdurre il dato.

3) Caso di rifiuto automatico con notifica di eccezione al mittente.
Ci è arrivata una segnatura in cui l'importa del documento indicata non è il base64 dello SHA256 (algoritmo dichiarato) ma il base64 dell'esadecimale dell'impronta SHA-256. Secondo le specifiche non ci sembra sia da accettare, cosa ne pensate?

Esempio
File: 001272009024070120220001.XML
Dimensioni: 1537 bytes
Impronta SHA256 (HEX):  d0a59ed9396ef84711937b228445df4bca65dd8ce2d4904a382610b72d87a650
Impronta MD5: 202a08bd92162d079d1415bec36e8729
Riferimento temporale UTC: 2022-01-13T09:58:35.953Z
Impronta SHA256 (base64):  0KWe2Tlu+EcRk3sihEXfS8pl3Yzi1JBKOCYQty2HplA=
in segnatura (sembra essere il base64 dell'impronta SHA256 (HEX)) 
ZDBhNTllZDkzOTZlZjg0NzExOTM3YjIyODQ0NWRmNGJjYTY1ZGQ4Y2UyZDQ5MDRhMzgyNjEwYjcyZDg3YTY1MA==

4) Tra gli algoritmi previsti per l'impronta ci sono anche gli HMAC ma per usarli (e per generare l'impronta per la verifica) dobbiamo avere una chiave. In quale tag / attributo è previsto si trovi questa chiave?

Ringrazio per la collaborazione
Saluti
Alessandra

**Comment by franthemanIT** [comment]
Leggo per caso. Avete trovato delle soluzioni? Sembrano tutte questioni interessanti, soprattutto 1 e 3 che riguardano la necessità di scartare automaticamente delle comunicazione per dei vizi formali in un file tecnico di accompagnamento. Questione spinosa.

Sul punto 2 chiedo, invece: la segnatura.xml non è da usare solo per comunicazioni fra AOO?
