### ISSUE TITLE
Servizio per validazione segnatura rispetto ai file inviati

### ISSUE THREAD

**Issue by franthemanIT** [AgID/protocollo-comunicazione-aoo#53]
Salve,
esiste un servizio per validare una segnatura anche rispetto ai file inviati?
Intendo: non solo correttezza formale dell'xml ma anche rispondenza delle impronte.

Chiedo perché ho un problema di continue eccezioni da un ente (solo lui) per impronte anomale e sarebbe utile capire chi sta sbagliando.

**Comment by vintra73** [comment]
No, non esiste un servizio di questo tipo
