### ISSUE TITLE
URL/URI dei namespace

### ISSUE THREAD

**Issue by franthemanIT** [AgID/protocollo-comunicazione-aoo#54]
Salve, nella definizione dei namespace (o come si vogliano chiamare i riferimenti a schemi XSD esterni) non potrebbe essere utile il puntamento all'xsd a cui ci si riferisce piuttosto che a degli indirizzi web che danno errore 404?
Forse, dico forse, aiuterebbe la validazione degli XML anche ai meno esperti.

Es.:
xmlns:msgprot="http://www.agid.gov.it/protocollo/messaggi/" 
xmlns:prot="http://www.agid.gov.it/protocollo/" 
targetNamespace="http://www.agid.gov.it/protocollo/messaggi/"

**Comment by vintra73** [comment]
In merito si evidenzia che quanto indicato afferisci al nome del namespace e non il riferimento allo schemaLocation
