### ISSUE TITLE
Numero di mittenti nella segnatura di protocollo

### ISSUE THREAD

**Issue by NENE76** [AgID/protocollo-comunicazione-aoo#56]
Buongiorno,
nell'XSD della segnature di protocollo è previsto 1 solo mittente.
Se ne inserisco più di uno la segnatura non viene validata.

Non si potrebbe adeguare l'XSD per prevedere quello che è un caso frequente?

**Comment by jackom83** [comment]
Non è chiaro lo scenario in cui si prevedono più mittenti, potrebbe fornirci ulteriori dettagli su cosa si intende?
