### ISSUE TITLE
Quesito su allegato 6 -  memorizzazione della conferma di protocollazione del messaggio di protocollo nel registro di protocollo

### ISSUE THREAD

**Issue by GianlucaGambioli** [AgID/protocollo-comunicazione-aoo#57]
Quando una Amministrazione Interoperabile mittente scrive ad un'altra Amministrazione Interoperabile destinataria, l'Amministrazione destinataria risponde con la "conferma di protocollazione del messaggio di protocollo" a questo punto L'AOO mittente cosa deve fare?
Deve protocollare a sua volta la ricevuta di protocollazione del destinatario o come previsto per le notifiche PEC va solo memorizzata ed associata al protocollo in uscita senza nuova protocollazione?

Lo scenario che crea il dubbio maggiore è questo, se una AOO centrale scrive alle sue AOO, territoriali che potrebbero essere centinaia (es Ragionerie territoriale, Agenzie, Corti tributarie), in modalità interoperabile queste risponderebbero ognuna con la propria conferma di protocollazione, se il mittente dovesse protocollare a sua volta tutte queste conferme, a fronte di un protocollo in uscita dovrebbe generare centinaia di protocolli in ingresso.  

Il punto riportato nell'allegato indica "Deve memorizzare" non specificando se questa attività deve essere svolta con una registrazione di protocollo automatica o impostando una semplice relazione.

_.......AOO mittente: Ricezione della conferma di protocollazione del messaggio di protocollo Nel caso in cui l’AOO destinatario non segnali anomalie **l’AOO mittente DEVE memorizzare la conferma di protocollazione del messaggio di protocollo nel registro di protocollo** per assicurare la persistenza dello stesso. Nel caso in cui l’AOO destinatario segnali anomalie l’AOO mittente DEVE ritenere la transazione non conclusa._

Resto in attesa di una gradita risposta.

**Comment by jackom83** [comment]
Va solo memorizzata ed associata al protocollo in uscita senza nuova protocollazione.
