### ISSUE TITLE
mittente / destinatario

### ISSUE THREAD

**Issue by franthemanIT** [AgID/protocollo-comunicazione-aoo#61]
Sarà perché manca una guida testuale del processo, un aggiornamento dell'allegato 6 insomma, ma personalmente trovo fuorviante e di difficile comprensione "mittente" e "destinatario" negli URL degli endpoint.
Quale e' il punto di vista adottato?

**Comment by jackom83** [comment]
"mittente" e "destinatario" sono utilizzati come prefissi per indicare le operation da implementare per il relativo ruolo

**Comment by franthemanIT** [comment]
Ok, quindi, anche guardando meglio la logica è questa:

Se ti contatto su un URL "/mittente" vuol dire che io ti sto contattando perché sei mittente di una comunicazione della quale voglio prelevare gli allegati, comunicarti l'esito o dirti che ho annullato il protocollo precedentemente staccato.

Se ti contatto su un URL "/destinatario" vuol dire che ti sto contattando nel tuo ruolo di destinatario, quindi per spedirti un messaggio o comunicarti che un messaggio precedentemente inviato l'ho annullato.
