### ISSUE TITLE
Applicazione delle LG del documento informatico: allegato 6

### ISSUE THREAD

**Issue by marco-deligios** [AgID/protocollo-comunicazione-aoo#9]
Un primo test di migrazione delle informazioni contenute nella segnatura di protocollo a norma circ. 60 verso il modello definito nell’allegato 6 delle LG mi ha fatto nascere alcune domande:

### Messaggi di ritorno
Nella circolare 60 il capitolo 8.3 era dedicato alla Struttura messaggi di ritorno scambiato tramite posta elettronica.

Nel caso la modalità di trasmissione sia posta elettronica quale deve essere la struttura dei messaggi di ritorno del protocollo informatico della AOO destinataria per soddisfare tutti i casi d’uso previsti dai flussi di comunicazione?

### Riferimenti esterni
Nella circolare 60 “_Un messaggio protocollato può contenere riferimenti esterni a documenti informatici reperibili per via telematica, […] Tali riferimenti esterni possono riguardare sia il documento primario che i documenti allegati ._”
Questa soluzione consentiva di gestire la trasmissione di documenti di grandi dimensioni sia tramite Posta elettronica, sia tramite Webservices in modalità asincrona senza incorrere in limiti del gestore di PEC e in timeout della comunicazione

Come è possibile gestire questa modalità di comunicazione rispettando le specifiche dell’allegato 6?

### Elemento Riferimenti
La circolare 60 prevedeva la presenza nel file di segnatura di un elemento **Riferimenti**, attraverso la quale era possibile fare riferimento a un messaggio precedentemente inviato dal destinatario per consentirgli la fascicolazione automatica del nuovo messaggio (Riferimenti/Messaggio/Identificatore)

Come è possibile gestire questa modalità di comunicazione rispettando le specifiche dell’allegato 6?

### Elemento Riservato
La circolare 60 prevedeva la presenza nel file di segnatura di un elemento **Riservato**: _Esprime la richiesta di trattamento riservato del messaggio protocollato. Può contenere un testo che descrive i motivi della richiesta_.

Come è possibile gestire questa modalità di comunicazione rispettando le specifiche dell’allegato 6?

### Elemento ContestoProcedurale
La circolare 60 prevedeva la presenza nel file di segnatura di un elemento **ContestoProcedurale**: _Indica un riferimento ad un contesto procedurale ovvero lo svolgimento di un generico complesso di attività amministrative in qualche modo collegate_. Attraverso il quale era possibile individuare la tipologia di procedimento alla quale si riferisce il messaggio (e, di conseguenza, gestire inoltri automatici).

Come è possibile gestire questa modalità di comunicazione rispettando le specifiche dell’allegato 6?

### Elemento PiuInfo
La circolare 60 prevedeva la presenza nel file di segnatura di un elemento **PiuInfo**: _L’elemento opzionale “PiuInfo” contiene ulteriori informazioni, che non è possibile associare ad altri elementi, relative all’elemento padre cui si riferisce. Qualora due o più amministrazioni stabiliscano di scambiarsi informazioni non previste tra quelle definite, esse possono estenderle con le informazioni specifiche stabilite di comune accordo utilizzando questo elemento_.

Come è possibile gestire questa modalità di comunicazione rispettando le specifiche dell’allegato 6?

**Comment by vintra73** [comment]
Nel ringraziarla per le osservazioni e nel renderci disponibili come AgID ad confronto diretto le anticipiamo le nostre in merito.

1. Messaggi di ritorno
Relativamente all'utilizzzo della PEC, che ci si auspica sia solo transitorio, fatto salva l'esigenza di aggiornare il type Segnatura definito nel namespace http://www.digitPa.gov.it/protocollo/ con il nuovo type SegnaturaInformaticaType definito nel namespace http://www.agid.gov.it/protocollo/ il protocollo di comunicazione, comprensivo degli oggetti dei messaggi scambiati previsti nella CIRCOLARE N. 60 DEL 23 GENNAIO 2013 dell'AgID, è da intendersi immutato.

2. Riferimenti esterni
Nell'ambito del contesto dei WS, obiettivo dell'allegato 6, non si è evidenziata l'esigenza di prevedere un disaccoppiamento tra il mesasggio inoltrato dalla AOO mittente e il documento primario e gli eventuali allegati. Di contro nell'ipotesi della PEC la segnalazione riportata ha la necessità di un approfondimento in quanto l'inoltro del solo URL (che comunque potrebbe essere veicolato nell'attributo nomeFile del type DocumentType) ci appare una soluzione non sicura in merito alla riservatezza del documento primario e degli eventuali allegati. 

3. Elemento Riferimenti
Nella volontà di rincodurre la segnatura di protocollo alla sua funzione originaria (referenziare un documento nell'ambito del sistema informativo della PA) abbiamo provveduto a semplificare ed eliminare molti degli attributi presenti nella precedente versione. In merito alla sua si suggerisce, nelle relazione tra specifiche AOO che condividono il popolamento e il cosumo di ulteriori attributi condivisi, di provvedere alla definizione di uno specifico type che estenda il type SegnaturaInformaticaType, ad esempio:

```
	<xs:complexType name="SegnaturaInformaticaCustomeType">
		<xs:complexContent>
			<xs:extension base="prot:SegnaturaInformaticaType">
				<xs:sequence>
					<xs:element name="elementCustom"/>
				</xs:sequence>
				<xs:attribute name="attributeCustom"/>
			</xs:extension>
		</xs:complexContent>
	</xs:complexType>
```
	
Un tale approccio ci sembra favorisca il riuso delle componenti implementate in quanto la business logic di consumo del type SegnaturaInformaticaType resta immutato.

4. Elemento Riservato
Fatto salvo quanto indicato al precedente punto 3, la gestione dei trattamenti riservati richiede un approfondimento in quanto la sola presenza di un flag non assicura la riservatezza dei documenti e degli allegati scambiati. 

5. Elemento ContestoProcedurale
Vale quanto indicato al precedente punto 3.

6. Elemento PiuInfo
Vale quanto indicato al precedente punto 3.

Nel confermare il nostro interesse per un confronto diretto di seguito i refenti AgID che può contattare.
- Guido Pera (pera@agid.gov.it)
- Vincenzo Travascio (vincenzo.travascio@agid.gov.it)

**Comment by franthemanIT** [comment]
Mi inserisco sul punto 3: la possibilità di indicare il numero di protocollo della comunicazione alla quale si sta rispondendo mi sembra che risponda pienamente alla funzione di "referenziare un documento nell'ambito del sistema informativo della PA", e già da prima dell'avvento dell'informatica.
Sarebbe quindi preferibile veicolare questa informazione nei type standard della segnatura e non demandarla a type specifici, oggetto di convenzioni particolari fra poche AOO (con conseguente moltiplicarsi di convenzioni e aumento della complessità da gestire).

**Comment by deligios** [comment]
@vintra73  mi pare di ricordare che l'elemento riferimenti citato da @franthemanIT sia stato ripristinato a seguito della call con i players giusto?

**Comment by vintra73** [comment]
@deligios in merito al fix-bug realizzato abbiamo rintrodotto l'element _SegnaturaInformatica\Intestazione\PrimaRegistrazione_  e l'element _SegnaturaInformatica\Riferimenti_ semplificando il datatype in 

<xs:complexType name="RiferimentiType">
		<xs:annotation>
			<xs:documentation>
				Dati per permettere al mittente di indicare il messaggio di protocollo ricevuto che ha determinato l'inoltro
				
				- Identificatore, i dati per identificare univocamente il messaggio di protocollo in attuazione all'art. 55 del DPR 445/2000
				- PrimaRegistrazione, si riferisce all'Identificatore di registrazione primario, cioè attribuito per la prima volta ad un documento protocollato che viene ritrasmesso più volte. Deve essere specificato solo se non coincide con l'Identificatore del messaggio protocollato.
				- Oggetto, sintesi dei contenuti di carattere giuridico, amministrativo e narrativo di un documento 
				- Classifica, la categoria del Titolario di classificazione associato al messaggio di protocollo 
			</xs:documentation>
		</xs:annotation>
		<xs:sequence>
			<xs:element name="Identificatore" type="prot:IdentificatoreType"/>
			<xs:element name="PrimaRegistrazione" type="prot:IdentificatoreType" minOccurs="0"/>
			<xs:element name="Oggetto" type="xs:string"/>									
			<xs:element name="Classifica" type="prot:ClassificaType" />			
			<xs:element name="Fascicolo" type="prot:FascicoloType" minOccurs="0" />
		</xs:sequence>		
	</xs:complexType>

**Comment by franthemanIT** [comment]
Grazie.
Mi pare di capire che la p.a. che intenda adeguarsi (o, meglio, verificare che chi gli fornisce il software si adegui correttamente), piu' che al testo pubblicato delle linee guida debba fare riferimento alla versione della segnatura presente su GitHub?
Io personalmente, particolarmente distratto, ho scoperto l'esistenza di un GitHub dedicato alla segnatura di protocollo per comunicazioni fra AOO piuttosto casualmente, siamo sicuri che tutte le p.a. ne siano a conoscenza e siano quindi in grado di verificare la conformità degli strumenti che usano?
Perche' - lo ricordo - la conformità degli strumenti (software) a qualsiasi normativa e' in capo all'amministrazione che usa quegli strumenti. e non ci sono "call con i players" che tengano (sempre che queste non vogliano sostituirsi a quella "certificazione" dei software che tanto sarebbe utile per le p.a. quanto sempre piu' accantonata come idea).

**Comment by franthemanIT** [comment]
Aggiungo che, reintrodotti i "riferimenti", sarebbe utile anche specificare la "semantica" del riferimento, il suo significato. Prevedere, insomma, un ulteriore elemento o un attributo del tipo "risponde a", "integra", "sostituisce".

Non mi è invece chiaro il senso di "PrimaRegistrazione": sembra che si assuma che un secondo invio di un medesimo documento debba generare un nuovo numero di protocollo.
